is_striving_for_api_consistency
WasatchPhotonics/Wasatch.PY pull request #76
Opened 2023-06-15 13:33 UTC by mzieg

I don't like adding weight to obvious 1-line convenience accessors but different methods following the same naming style are returning different types.

2023-06-15 13:36 UTC, mzieg commented on wasatch/FeatureIdentificationDevice.py
>          """
This is an exception to the rule.

2023-06-15 13:38 UTC, mzieg commented
I would be fine deleting all the "-> bool" when there are no exceptions :-)  Maybe we add a nomenclature to signify methods returning SpectrometerResponse?  The class itself was a good idea.

2023-06-15 13:48 UTC, mzieg commented
Note that FID.can_laser_fire() technically falls under the "has_" and "is_" nomenclature too (returns SpectrometerResponse, so technically another exception, but I understand why that was done).

2023-06-19 13:43 UTC, samiebee43 requested changes
https://realpython.com/lessons/type-comments/

2023-06-22 14:52 UTC, mzieg commented on wasatch/DetectorRegions.py
> +    def has_region(self, region) -> bool:
fixed

2023-06-23 13:07 UTC, samiebee43 approved these changes

2023-06-23 15:15 UTC, merged